### ISSUE TITLE
Slower then previous one that was with Retrofit + Okhttp

### ISSUE THREAD

**Issue by ishroid** [OneDrive/onedrive-sdk-android#24]
I am using onedrive sdk from last 4 years, I used all updated version, But i found this version very slow after expanding thumbnails.

A previous version of SDK that was released for a while used Retrofit + OkHttp , I downloaded it and used it ,that was faster then this version and first one.

I think serializing and de-serializing of json object and unnecessary huge response taking time.

Make New SDK Faster then ever.

**Comment by peternied** [comment]
Thanks for reporting @ishratkhan 

I would not expect you to see any decreases in performance using this SDK.  In fact if you've been using the LiveSDK with LiveConnect API this SDK should be considerable faster as the service is optimized for speed.  Can you give me an idea specific scenario and the differences in speed so I can look into it? eg GET v5.0/me/files of an account with 150 files, with thumbnails expanded took 1000ms before, GET drive/root takes 2000ms.

A couple of quick perf optimization that your application can make:
- Using 'select' statements
  - If you are retrieving only the data that your application is indenting on using, it should be less traffic over the wire and less overhead when deserializing the responses.
- Use the Sync Changes API
  - [Sync Changes](https://dev.onedrive.com/items/view_delta.htm) is the fastest way to determine what changes have been done to a users OneDrive since your application last connected to the service.

**Comment by ishroid** [comment]
Thanks for suggestion @peternied 

I think Sync Changes is the best way that i really needed i didn't know about it, thanks for sharing information about it,

using your suggestion my app  going to be faster then ever.

I will update you about the scenario,

Thank you very much
