### ISSUE TITLE
Silent Login

### ISSUE THREAD

**Issue by 1gravity** [OneDrive/onedrive-sdk-android#49]
There's currently no way to silently login.
Assuming the user has previously signed in but revoked the access to OneDrive, there should be a way for an app to control when the authentication workflow starts. As it stands the loginAndBuildClient always tries to invoke the login screen but an app/user should not be forced to login, the control over when the login happens should remain with the app. This is possible with all competing cloud storage providers I've integrated with so far (Google Drive, DropBox).

**Comment by peternied** [comment]
This is a good callout, thanks!

**Comment by cpore** [comment]
I'd like to second this enhancement. OneDriveClient and its builder need to be decoupled from an Activity. My team needs to use the client in a service. This is a blocking issue for us. Any suggested work around?

**Comment by peternied** [comment]
The [`IAuthenticator`](https://github.com/OneDrive/onedrive-sdk-android/blob/master/onedrivesdk/src/main/java/com/onedrive/sdk/authentication/IAuthenticator.java) is the only consumer of the activity parameter via the builder, if you created your own implementation you could ignore the activity parameters entirely and just pass a null value in the builder.

**Comment by 1gravity** [comment]
I'm using a different DisambiguationAuthenticator class if I want a silent login. Maybe this helps someone:

```

public class SilentDisambiguationAuthenticator extends DisambiguationAuthenticator {

    private static final String sErrorMsg = "Interactive login not allowed";

    public SilentDisambiguationAuthenticator(final MSAAuthenticator msaAuthenticator,
                                             final ADALAuthenticator adalAuthenticator) {
        super(msaAuthenticator, adalAuthenticator);
    }

    /**
     * Starts an interactive login asynchronously.
     *
     * DISABLED.
     */
    @Override
    public void login(final String emailAddressHint, final ICallback<IAccountInfo> loginCallback) {
        throw new ClientException(sErrorMsg, new IllegalStateException(sErrorMsg), OneDriveErrorCodes.GeneralException);
    }

    /**
     * Starts an interactive login.
     *
     * DISABLED.
     */
    @Override
    public synchronized IAccountInfo login(final String emailAddressHint) throws ClientException {
        throw new ClientException(sErrorMsg, new IllegalStateException(sErrorMsg), OneDriveErrorCodes.GeneralException);
    }

}

```

**Comment by 4b69** [comment]
Was there any progress made on this? It's quite jarring to be prompted to re-allow the same permissions for an app on a onedrive account when gdrive/dropbox/etc can all do it silently.

**Comment by peternied** [comment]
@p0087 @cpore @1gravity  With the release of the [Microsoft Graph SDKs for Android](https://github.com/microsoftgraph/msgraph-sdk-android), there was a slight redesign of the configuration/authentication pattern that does not require passing an activity reference into the service client object.

Note; the Microsoft Graph has some incomplete scenarios compared to calling the OneDrive API directly, we are ever expanding the capabilities of both OneDrive and the Microsoft Graph Service.  For an example of how to convert, see this fork of the [OneDrive Explore for Android](https://github.com/microsoftgraph/onedrive-explorer-android)

**Comment by sw-dev1** [comment]
@peternied About your suggestion above concerning the IAuthenticator: looking at its implementations like MSAAuthenticator, creating an implementation from scratch does not seem to be straightforward. Would subclassing MSAAuthenticator be a way of moving toward an Activity-independent client? Thanks.

**Comment by sw-dev1** [comment]
@peternied I tried subclassing MSAAuthenticator and stumbled onto the problem that the sharedPreferences are retrieved through an activity handle. The method using this handle is private, i.e. not possible to override and change to something without an activity. 
The functionality for signing in and everything that needs user interaction is still needed, so somehow I need to keep the MSAAuthenticator. Testing shows that silent login succeeds most of the time, only it has to be called from an activity. This suggests that it could succeed if called from a service, but how?
Any specific ideas how to move forward?

Thanks.

**Comment by peternied** [comment]
Thanks for looking into this @sw-dev1 that is a challenge.  It sounds like it might also be possible to make the MSAAuthenticator more extensible for these purposes and I would be happy to review a pull request.

Would it be possible for you to duplicate and modify the MSAAuthenticator class for your purposes instead of sub-classing it within your project?  This would allow you to modify the references to the activity and instead use a context, if you want to keep the shared preferences functionality.

**Comment by sw-dev1** [comment]
Good thought @peternied, I had just started with duplicating MSAAuhenticator. Next was a need to modify MSAAccountInfo to accept the new class in its constructor. The LiveAuthClient can be constructed with a Context, so it should be possible to pass an Application context for our purpose. Now the next challenge: the IAuthenticator needs to take an Application context in the init(). We need this in order to be able to pass an Application context to loginAndBuildClient(...) of OneDriveClient (which also needs to be modified in turn to call the modifed init).

**Comment by peternied** [comment]
Could you call `init` from an activity, and then use activity.getApplicationContext() to provide the backing context you would need instead of the activity context in your version of MSAAuthenticator?

**Comment by sw-dev1** [comment]
Sure, but if the app is a service only, after a time it would fall back to asking the user to open the activity because this is the only way to rebuild the client.  In my tests (an activity and a service) all goes well until at some point in time the service wants to use the OneDriveClient through a handle in the application and it is null. Not always, mostly it is available for about an hour or so. I have been wondering why the client becomes null after a while. Is it reasonable to expect the OneDriveClient handle stored in the app to be always available?

**Comment by peternied** [comment]
Hmm, that hour window sounds like its associated with the timeout on the access token which is also an hour.  Are you using the `offline_access` scope so you can silently re-authenticate?

RE: Null OneDriveClient, the client is not 'nullifed', it should be usable within a service context provided you have the plumbing in place for interactive login.  Sounds like something wrong with the application lifecycle.

**Comment by sw-dev1** [comment]
Yes, I am using the  offline_access  scope. The application lifecycle is certainly the reason why the client gets null (thanks for the hint). This is determined by the design of Android. If an application holds an activity and a service, if both are inactive, the application will be eventually also killed with the process that holds it. If the service is bound, it will be reactivated later by the system and the application's onCreate() will be called. This is where we need to call loginAndBuildClient with the application context. Would you be willing to extend the IAuthenticator interface for this purpose?

BTW, I have just published an app in Play Store that has a workaround. You can write me an email if you are interested to know more. Cheers.

**Comment by sw-dev1** [comment]
Just to let you know, I have now a working silent login implementation in the app Bookmarks for OneDrive.

**Comment by alexeyvasilyev** [comment]
So is there any progress on this issue?

I have integrated Amazon Drive, Google Drive, Dropbox clouds. And all of them support silent login. Even obsolete MS Live SDK for Android didn't have this issue.

I want OneDrive to be used as a service and want to control when authentication dialog should be shown.

**Comment by jefftharris** [comment]
I too am looking to use the new OneDrive SDK for a sync service and need a way to create the client without an activity using a previous logged-in session.

**Comment by daboxu** [comment]
hi @alexeyvasilyev @jefftharris, will the [Microsoft Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-android#22-create-an-iauthenticationprovider-object) help you as you want to integrate OneDrive as a service in this case? You can implement the IAuthenticationProvider interface to have a customized oauth process.

**Comment by jefftharris** [comment]
Implementing an entirely custom oauth process seems overkill.  Looking in OneDriveClient and MSAAuthenticator, there are opportunities to use a base Context which services have rather than an Activity.  MSAAuthenticator can use a Context to create its LiveAuthClient and then simply return a null account info from the login methods if its context is not an Activity. OneDriveClient already tries to do a silent login to reuse previous credentials.

I'm not seeing how the graph SDK can help as it uses different authentication interfaces which are not tied tied to an Activity.  A copy of MSAAuthenticator to work with a Context and optional Activity may be needed.

**Comment by cormal** [comment]
We had the same problem and it would be nice to see a solution to as much. In the interim we ended  up using the ActivityLifecycleCallbacks to monitor the current activity and simply pass that to the loginandbuiltclient running on a background service. We then override the IAccountInfo login to return null to an exception which prevents the login screen opening and simply catch and deal with the login failure.  This way the background service has reference to an activity but doesn't have an impact on it. It also keeps the app in the background when it has lost focus and the reference is passed. Not the nicest solution but it works for now.

**Comment by rupbhangale** [comment]
Hi,
We are trying to integrate opendrive sdk in android application, but stuck at authentication part.
Facing the same issue i.e "Failed silent login, interactive login required" at the time of authentication.

Followed the exact steps for authentication given in  this document. 
Client id used :: 00000000-0000-0000-0000-000000000000 format.

**Comment by daboxu** [comment]
hi @rupbhangale please register your application on https://apps.dev.microsoft.com/ to have your own app ID. Tutorial of register your app is here: https://github.com/OneDrive/onedrive-sdk-android#2-getting-started

**Comment by BenjaminPiette** [comment]
Just cloned the whole OneDriveClient class to be able to customize it and get more flexibility regarding connection status / silent login.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #172 for more information
