### ISSUE TITLE
After an item is deleted through the API, it is included in the next delta.

### ISSUE THREAD

**Issue by sw-dev1** [OneDrive/onedrive-sdk-android#99]
Except for the case of deletion, all other changes through the API (with the same client) are not included in the next delta. Is the different behavior for deletion deliberate?

**Comment by peternied** [comment]
Those items that were deleted and appear in the delta enumerate will have a `deleted` facet.  This is a feature for applications that are building offline sync clients and need to know when to remove items from disk.

If you don't mind me asking how are you using the delta API?

**Comment by sw-dev1** [comment]
I am kind of building a sync client. I get the delta, process all server changes first, then process local/client-side changes. The next delta is empty if there are only newly created items and/or changes in the client-to-server direction. This behavior is really good because (please correct me if I am wrong) the delta includes only server changes caused by clients other than the client requesting the delta.
In the case of deletions however they are in the delta for the deleting client which results in the calling client trying to repeat the local deletion (it can recognize the deletion is not from another client only with additional code) which caused the server deletion previously. The successful server deletion was assumed at the time of run of the success method of the callback for the deletion request.

**Comment by peternied** [comment]
```
delta includes only server changes caused by clients other than the client requesting the delta
```

The delta api does not take into consideration the caller, the only consideration is the delta token that which could be considered marker in time of what changes this client is aware of, you can imagine that for each change there is a delta token created.

Quick example:

Change: Original State!
Delta Token: **214B5F50**

Change: Add File X.txt
Delta Token: 678B7522

Change: Add File Y.txt
Delta Token: _12CE1052_

Change: Delete File X.txt
Delta Token: DA88B0B7

Change: Modify File Y.txt
Delta Token: 0A79324C

If the client started @**214B5F50**, the original state, and then queried the delta api the response would include X.txt@0A79324C with a deleted facet and Y.txt@0A79324C .  This API coalesces operations based on the difference between delta tokens, so the creation of X.txt would not be seen and the modification of Y.txt would not be seen.

If the client started @_12CE1052_, after X.txt and Y.txt were created, then queried the delta api the response would include the X.txt@0A79324C with a deleted facet, and Y.txt@0A79324C since it was modified.  Thanks for reading along in this explicit definition. 

As you describe handling the service side changes and then modifying the client you are working in the pattern that we recommend for using the delta api.  Our [delta api documentation](https://dev.onedrive.com/items/view_delta.htm) has more details on error scenarios and validation if there are aspects that are not clear.

**Comment by sw-dev1** [comment]
Thanks for this explanation. I realized that I was wrong in my assumption that deletions were handled differently. 
As you explained, all changes uploaded to server by the client are included in the next delta request from the same client. As they are not distinguishable from the changes made by other clients, the client that caused them will have to handle them again, reapplying locally the changes previously uploaded to the server. Any suggestion how to avoid this second sync? The problem is that if there is a second local change on a changed item in the time between the two deltas, it will be overwritten by the server changes (re)applied with the second delta.

**Comment by peternied** [comment]
The scenario you are describing is conflict management, and their are a many ways depending on what the application knows about the file and the service changes to handle the conflict.

An application could select a file based on metadata and prune the other from the 'sync history', other resolutions could be duplicating files and requiring the user manage the conflicts via some conflict management interface.

**Comment by sw-dev1** [comment]
I understand. Thank you.
